GET http://localhost:3001/api/tours

###
GET http://localhost:3001/api/tours/2

###
DELETE http://localhost:3001/api/tours/625f6f00d9d7920e148a8469

###
POST http://localhost:3001/api/tours
Content-Type: application/json

{
    "city": "Neuschwanstein",
    "country": "Germany",
    "tripName": "Neuschwanstein Castle & Highline 179 Bridge" ,
    "details": "You have been waiting eagerly for our Spain Trip! The time has come! We are going to Lloret de Mar and Barcelona! We have a great HOTEL with a swimming pool at Lloret de Mar 250 meters away from the beach! We have double and triple rooms according to your wishes. Breakfast Buffet & Dinner Buffet are included. It is not a hostel this time! We are going on holiday everyone should relax! :) Lloret de Mar:At the beginning you are most probably asking 'what the hell is Lloret de Mar'. Lloret de Mar is a small town at Costa Brava beach where all the young people from Germany, France, England and all over the world travel to celebrate their school degree. We are always the oldest people in Lloret de Mar and everyone is young & energetic! The people are making party in the morning, at noon, in the afternoon, at night and at the breakfast party again! :)",
    "imgs": [
        "https://d2j6dbq0eux0bg.cloudfront.net/images/13115220/1092024350.jpg",
        "https://d2j6dbq0eux0bg.cloudfront.net/images/13115220/1092025148.jpg"
    ],
    "price": 70,
    "ratings": 5
}

###
PUT http://localhost:3001/api/tours/625f6e86d9d7920e148a8466
Content-Type: application/json

{
    "imgs" : [
        "https://images.unsplash.com/photo-1610016302534-6f67f1c968d8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1075&q=80", 
        "https://images.unsplash.com/photo-1621947502614-2ccd0fdd0c20?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1075&q=80"
    ]
}